import streamlit as st
import os
import pandas as pd

from utils.session_manager import SessionManager


def show_reports():
    from components.ui import page_title
    page_title(
        ":material/analytics: Reports",
        "View and download AI generated comparison reports."
    )

    # =====================================
    # CURRENT ANALYSIS
    # =====================================

    analysis = SessionManager.get_analysis()

    if analysis:

        metrics = analysis["metrics"]

        c1, c2, c3, c4 = st.columns(4)

        with c1:
            st.metric(
                "Parameters Compared",
                metrics["parameters"]
            )

        with c2:
            st.metric(
                "Matches Found",
                metrics["matches"]
            )

        with c3:
            st.metric(
                "Changes Found",
                metrics["changes"]
            )

        with c4:
            st.metric(
                "Repository",
                metrics["repository"]
            )

    else:

        st.info(
            "Run an analysis first."
        )

        return

    st.divider()

    # =====================================
    # REPORT PREVIEW
    # =====================================

    st.subheader(":material/preview: Report Preview")

    try:

        df = pd.read_excel(
            analysis["report_path"]
        )

        st.dataframe(

            df.head(10),

            use_container_width=True,

            hide_index=True

        )

    except Exception as e:

        st.error(str(e))

    st.divider()

    # =====================================
    # DOWNLOAD REPORT
    # =====================================

    st.subheader(":material/download: Download Report")

    with open(
        analysis["report_path"],
        "rb"
    ) as file:

        st.download_button(

            label="📥 Download Excel Report",

            data=file,

            file_name="Product_Analysis_Report.xlsx",

            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",

            use_container_width=True

        )

    st.divider()

    # =====================================
    # REPORT DETAILS
    # =====================================

    st.subheader(":material/description: Report Details")

    report_size = os.path.getsize(
        analysis["report_path"]
    ) / 1024

    st.write(
        "**File Name:** Product_Analysis_Report.xlsx"
    )

    st.write(
        f"**File Size:** {report_size:.2f} KB"
    )

    st.write(
        "**Generated By:** Product Change Analyzer"
    )

    st.write(
        "**Status:** Completed"
    )

    st.divider()

    # =====================================
    # FUTURE FEATURES
    # =====================================

    st.subheader(":material/rocket_launch: Coming Soon")

    st.write("• PDF Report Export")

    st.write("• AI Executive Summary")

    st.write("• Business Impact Dashboard")

    st.write("• Compliance Report")

    st.write("• Actuarial Change Report")